HR/urls.py
from django.contrib import admin
from django.urls import path, include
from core.dashboard.views import DashboardView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.login.url')),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings
from core.dashboard.views import DashboardView
# from core.erp.views import *


urlpatterns = [
    path('', DashboardView.as_view(), name='dashboard'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('admin/', admin.site.urls),
    path('login/', include('core.login.url')),
    path('erp/', include('core.erp.urls')),
    path('user/', include('core.user.url')),
    path('security/', include('core.security.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/dashboard/urls.py
# from core.dashboard.views import DashboardView
# from django.urls import path
#
# urlpatterns=[
#     path('/', DashboardView.as_view(), name='home')
# ]

core/erp/urls.py
from django.urls import path

from core.erp.views.candidate.views import *
from core.erp.views.company.views import CompanyUpdateView

from core.erp.views.departaments.view import *
from core.erp.views.empleados.views.view import *
from core.erp.views.puesto_trabajo.views import *
from core.erp.views.salary.view import *
from core.erp.views.seleccionados.views import *
from core.erp.views.turnos_trabajo.views import *
from core.erp.views.vacante.views import *
from core.erp.views.asistencia.views import *
from core.erp.views.descuentos.view import *
from core.erp.views.Vacations.views import *

app_name = 'erp'

urlpatterns = [
    # Departamentos
    path('departaments/list/', DepartamentListView.as_view(), name='departaments_list'),
    # path('departaments/create/', DepartamentCreateView.as_view(), name='departaments_create'),
    # path('departaments/edit/<int:pk>/', DepartamentUpdateView.as_view(), name='departaments_edit'),
    # path('departaments/delete/<int:pk>/', DepartamentDeleteView.as_view(), name='departaments_delete'),

    # Puesto_trabajo
    path('puesto/list/', PositionsJobListView.as_view(), name='position_list'),
    path('puesto/add/', PositionsJobCreateView.as_view(), name='position_create'),
    path('puesto/update/<int:pk>/', PositionsJobUpdateView.as_view(), name='position_update'),
    path('puesto/delete/<int:pk>/', PositionsJobDeleteView.as_view(), name='position_delete'),

    # Turno trabajo
    path('turno_trabajo/list/', TurnJobListView.as_view(), name='turno_trabajo_list'),
    path('turno_trabajo/add/', TurnJobCreateView.as_view(), name='turno_trabajo_create'),
    path('turno_trabajo/edit/<int:pk>/', TurnJobUpdateView.as_view(), name='turno_trabajo_update'),
    path('turno_trabajo/delete/<int:pk>/', TurnJobDeleteView.as_view(), name='turno_trabajo_delete'),

    # Candidatos
    path('candidato/list/', CandidateListView.as_view(), name='candidatos_list'),
    path('candidato/add/', CandidateCreateView.as_view(), name='candidatos_create'),
    path('candidato/edit/<int:pk>/', CandidateUpdateView.as_view(), name='candidatos_update'),
    path('candidato/delete/<int:pk>/', CandidateDeleteView.as_view(), name='candidatos_delete'),

    # Vacantes
    path('vacante/list/', VacantsListView.as_view(), name='vacante_list'),
    path('vacante/add/', VacantsCreateView.as_view(), name='vacante_create'),
    path('vacante/edit/<int:pk>/', VacantsUpdateView.as_view(), name='vacante_update'),
    path('vacante/delete/<int:pk>/', VacantsDeleteView.as_view(), name='vacante_delete'),
    path('vacante/apply/<int:vacant_id>/', ApplyVacants.as_view(), name='vacante_apply'),
    path('vacante/apply/form/',  page_thanks, name='page_thanks'),
    # path('vacante/apply/<int:vacant_id>/', VacantsDeleteView.as_view(), name='vacante_delete'),


    # Seleccionados

    path('select/list/', SelectListView.as_view(), name='select_list'),
    path('select/add/', SelectCreateView.as_view(), name='select_create'),
    path('select/edit/<int:pk>/', SelectUpdateView.as_view(), name='select_update'),
    path('select/delete/<int:pk>/', SelectDeleteView.as_view(), name='select_delete'),

    # Empleados
    path('empleados/list/', EmpleadoListView.as_view(), name='empleados_list'),
    path('empleados/add/', EmpleadoCreateView.as_view(), name='empleados_create'),
    path('empleados/edit/<int:pk>/', EmpleadoUpdateView.as_view(), name='empleados_update'),
    path('generar_informe_empleados/', generar_informe_empleados, name='generar_informe_empleados'),
    path('empleados/report/<int:pk>/', EmpleadoInformeView.as_view(), name='reporte_empleado'),


    # Asistencia
    path('asistencia/list/', AssistanceListView.as_view(), name='asistencia_list'),
    path('asistencia/add/', AssistanceCreateView.as_view(), name='asistencia_create'),
    path('asistencia/update/<str:date_joined>/', AssistanceUpdateView.as_view(), name='asistencia_update'),
    path('asistencia/delete/<str:start_date>/<str:end_date>/', AssistanceDeleteView.as_view(), name='asistencia_delete'),

    # Conceptos de Descuentos
    path('descuento/list/', DescuentosListView.as_view(), name='descuento_list'),
    path('descuento/add/', DescuentosCreateView.as_view(), name='descuento_create'),
    path('descuento/update/<int:pk>/', DescuentosUpdateView.as_view(), name='descuento_update'),
    path('descuento/delete/<int:pk>/', DescuentoDeleteView.as_view(), name='descuento_delete'),

    path('salary/list/', SalaryListView.as_view(), name='salary_list'),
    path('salary/add/', SalaryCreateView.as_view(), name='salary_create'),

    # Vacations
    path('vacations/list/', VacationsListView.as_view(), name='vacations_list'),
    path('vacations/add/', VacationsCreatView.as_view(), name='vacations_create'),
    path('vacations/edit/<int:pk>/', VacationsUpdateView.as_view(), name='vacations_update'),
    path('vacations/generar_reporte_vacaciones/<int:pk>/', generate_pdf_report, name='generar_reporte_vacaciones'),

    #Company
    path('company/update/', CompanyUpdateView.as_view(), name='company_update')


]

core/dashboard/models.py
from django.db import models

# Create your models here.

core/user/models.py
import uuid
from core.erp.models import Employee
from crum import get_current_request
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.forms import model_to_dict
from config.settings import MEDIA_URL, STATIC_URL


class User(AbstractUser):
    image = models.ImageField(upload_to='users/%Y/%m/%d', null=True, blank=True)
    token = models.UUIDField(primary_key=False, editable=False, null=True, blank=True)
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE, verbose_name="Employee", unique=False,null=True)


    def get_image(self):
        if self.image:
            return '{}{}'.format(MEDIA_URL, self.image)
        return '{}{}'.format(STATIC_URL, 'img/empty.png')

    def toJson(self):
        item = model_to_dict(self, exclude=['password', 'user_permissions',  'last_login'])
        if self.last_login:
            item['last_login'] = self.last_login.strftime('%Y-%m-%d')
        item['date_joined'] = self.date_joined.strftime('%Y-%m-%d')
        item['image'] = self.get_image()
        item['groups'] = [{'id': g.id, 'name': g.name} for g in self.groups.all()]
        item['full_name'] = self.employee.get_full_name()

        if self.employee:
            item['employee__firstname'] = self.employee.person.firstname
            item['employee__lastname'] = self.employee.person.lastname
            self.first_name = self.employee.person.firstname
            self.last_name = self.employee.person.lastname
        return item


    def get_group_session(self):
        try:
            request = get_current_request()
            group = self.groups.all()
            if group.exists():
                if 'group' not in request.session:
                    request.session['group'] = group[0]
        except:
            pass

    

core/dashboard/views.py
import datetime
import json
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Sum, FloatField
from django.db.models.functions import Coalesce
from django.http import HttpResponse, JsonResponse
from django.views.generic import TemplateView
from core.erp.models import *
from django.utils import timezone
from core.erp.views.Vacations.views import send_email_vacation_finished, send_reminder_vacation_ending

# Create your views here.

class DashboardView(LoginRequiredMixin, TemplateView):
    template_name = 'dashboard.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            today = timezone.now().date()
            tomorrow = today + datetime.timedelta(days=1)
            vacations_to_complete = Vacations.objects.filter(end_date=today)
            vacations_to_remind = Vacations.objects.filter(end_date=tomorrow, state_vacations='Acceptada')
            for vacations in vacations_to_remind:
                if  not vacations.reminder_sent:
                    send_reminder_vacation_ending(vacations)
                    vacations.reminder_sent = True
                    vacations.save()
            for vacations in vacations_to_complete:
                if vacations.state_vacations != 'Finalizada':
                    vacations.state_vacations = 'Finalizada'
                    vacations.save()
                    send_email_vacation_finished(vacations)
                employee = vacations.empleado
                if vacations.end_date == today:
                    employee.estado = 'Contratado'
                    employee.save()
                
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, *args, **kwargs):
        request.user.get_group_session()
        # 
        # print('se envio')
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        data = {}
        action = request.POST['action']
        try:
            if action == 'get_graph_salaries_by_year':
                data = []
                year = datetime.datetime.now().year
                for month in range(1, 13):
                    result = SalaryDetail.objects.filter(salary__month=month, salary__year=year).aggregate(
                        result=Coalesce(Sum('total_amount'), 0.00, output_field=FloatField())).get('result')
                    data.append(float(result))
            else:
                data['error'] = 'No ha seleccionado ninguna opción'
        except Exception as e:
            data['error'] = str(e)
        return HttpResponse(json.dumps(data), content_type='application/json')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Panel de administración'
        context['salaries'] = SalaryDetail.objects.filter().order_by('-id')[0:10]
        context['year'] = datetime.datetime.now().year
        context['month'] = MONTHS[datetime.datetime.now().month][1]
        context['asistance'] = AssistanceDetail.objects.filter().order_by('-id')[0:10]
        context['positions'] = EmployeePositions.objects.all().count()
        context['areas'] = Departments.objects.all().count()
        context['headings'] = Headings.objects.all().count()
        context['employees'] = Employee.objects.all().count()
        return context

templates/basic.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <meta http-equiv="x-ua-compatible" content="ie=edge"/>
    <link rel="icon" href="{% static 'img/favicon.ico' %}" type="image/png"/>
    <title>{{ title }}</title>
    <!-- Font Awesome Icons -->
    <!-- Functions -->


{#    <link rel="stylesheet" href="{% static 'lib/adminlte-3.0.4/plugins/font-awesome-5.11.1/css/all.min.css' %}"/>#}
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'lib/adminlte-3.0.4/css/adminlte.min.css' %}"/>
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet"/>
    <!-- jQuery -->
    <script src="{% static 'lib/adminlte-3.0.4/plugins/jquery/jquery.min.js' %}"></script>
    <!-- AdminLTE App -->
    <!-- Sweetalert2 -->
    <script src="{% static 'lib/sweetalert2-9.10.0/sweetalert2.all.min.js' %}"></script>
    <script src="{% static 'lib/jquery-loading-overlay-2.1.7/js/loadingoverlay.min.js' %}"></script>
    <script src="{% static 'lib/jquery-confirm-3.3.4/js/jquery-confirm.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'lib/jquery-confirm-3.3.4/css/jquery-confirm.min.css' %}"/>
    <!-- My css -->

    <link rel="stylesheet" href="{% static 'css/mycss.css' %}"/>

    <link rel="stylesheet" href="{% static 'lib/fontawesome-6.1.1/css/all.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'lib/jquery-ui-1.12.1/jquery-ui.css' %}"/>
    <!--Javascript-->
    <script src="{% static 'lib/jquery-ui-1.12.1/jquery-ui.min.js' %}"></script>
   <script src="{% static 'lib/bootstrap-4.6.0/js/popper.min.js' %}"></script>
    <script src="{% static 'lib/bootstrap-4.6.0/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'lib/adminlte-3.0.4/js/adminlte.min.js' %}"></script>
    <script src="{% static 'js/functions.js' %}"></script>

    <!-- Block head -->
    {% block head %} {% endblock %}
</head>
</html>
<script src="{% static 'js/main.js' %}"></script>
{% block body %} {% endblock %}

templates/body.html
{% extends 'basic.html' %}
{% block body %}
<body class="hold-transition sidebar-mini layout-fixed">

        <div class="wrapper">
            <!-- Header -->
            {% include 'includes/navbar.html' %}
            <!-- Sidebar -->
            {% include 'sidebar.html' %}
            <!-- Content -->
            <div class="content-wrapper">
                <!--Block breadcrumb-->
                <section class="content-header">
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-sm-12">
                                <!--Block breadcrumb-->
                                {% block breadcrumb %}
                                    <div class="card">
                                        <nav aria-label="breadcrumb">
                                                <ol class="breadcrumb">
                                                    <li class="breadcrumb-item">
                                                        <a href="{% url 'dashboard' %}"><i class="fas fa-home"></i>
                                                            Panel</a>
                                                    </li>
                                                    <li class="breadcrumb-item"><a href="{{ list_url }}">{{ entity }}</a>
                                                    </li>
                                                </ol>
                                            </nav>
                                    </div>

                                {% endblock %}
                            </div>
                        </div>
                    </div>
                </section>
                <div class="content">
                    <div class="container-fluid">
                        {% block content %}

                        {% endblock %}
                    </div>
                </div>
            </div>
            <!-- Footer -->
            {% include 'footer.html' %}
        </div>
        <!-- Block javascript -->
        {% block javascript %}

        {% endblock %}
        <script>
            {% if messages %}
                var html = '<p>';
                {% for message in messages %}
                    html += '{{ message }}<br>';
                {% endfor %}
                html += '</p>';
                Swal.fire({
                    title: 'Error!',
                    html: html,
                    icon: 'error'
                });
            {% endif %}
    </script>
</body>
{% endblock %}

templates/delete.html
{% extends 'layouts.html' %}
{% load widget_tweaks %}
{% block content %}

   <form class="form" method="post" action="." autocomplete="off">
        <div class="card ">
            <div class="card-header">
                <h3 class="card-title">
                    <i class="fas fa-info-circle"></i>
                    {{ title }}
                </h3>
            </div>
            <div class="card-body" style="display: block;">
                <div class="container-fluid">
                    {% csrf_token %}
                    {% block delete_content %}
                        <p class="text-center font-weight-bold mt-3">
                            <i class="fas fa-trash fa-3x"></i><br><br>
                            ¿Estas seguro de eliminar el registro  {{ object.id }}?
                        </p>
                    {% endblock %}
                </div>
            </div>
            <div class="card-footer">
                {% block buttons %}
                    <button type="submit" class="btn btn-primary btn-flat">
                        <i class="fas fa-check-circle"></i> Si, Aceptar
                    </button>
                    <a href="{{ list_url }}" class="btn btn-danger btn-flat">
                        <i class="fas fa-times"></i> Cancelar
                    </a>
                {% endblock %}
            </div>
        </div>
    </form>
    <script type="application/javascript">
        $(function () {
            $('form').on('submit', function (event) {
                event.preventDefault();
                var params = new FormData(this);
                var args = {
                    'params': params,
                    'content': '¿Estas seguro de eliminar el registro?',
                    'success': function () {
                        location.href = '{{ list_url }}';
                    }
                };
                submit_with_formdata(args);
            });
        });
    </script>
{% endblock %}

templates/footer.html
{% load tz %} {# Cargar la etiqueta de zona horaria #}
<footer class="main-footer text-center">
    <strong>Dios te bendiga</strong> <br>
    <strong>Copyright &copy; {% now "Y" %} <span>Human Recruiter</span> Todos los derechos reservados</strong><br>
    <a> Desarrollado por: <strong>Joel Germán</strong></a>
</footer>

templates/form.html
{% extends 'body.html' %}
{% load static %}
{% block head %}


    <link rel="stylesheet" href="{% static 'lib/formvalidation-1.9.0/css/formValidation.min.css' %}">
    <script src="{% static 'lib/formvalidation-1.9.0/js/es6-shim.min.js' %}"></script>
    <script src="{% static 'lib/formvalidation-1.9.0/js/FormValidation.min.js' %}"></script>
    <script src="{% static 'lib/formvalidation-1.9.0/js/plugins/Bootstrap.min.js' %}"></script>
    <script src="{% static 'lib/formvalidation-1.9.0/js/locales/es_ES.min.js' %}"></script>

    {% block head_form %}
        <link href="{% static 'lib/select2-4.0.13/css/select2.min.css' %}" rel="stylesheet"/>
        <link href="{% static 'lib/select2-4.0.13/css/select2-bootstrap4.min.css' %}" rel="stylesheet"/>
        <script src="{% static 'lib/select2-4.0.13/js/select2.min.js' %}"></script>
        <script src="{% static 'lib/select2-4.0.13/js/i18n/es.js' %}"></script>

    {% endblock %}

{% endblock %}
{% block content %}
    <form method="post" action="." id="frmForm" data-url="{{ list_url }}">
        <input type="hidden" name="action" value="{{ action }}">
        <div class="card card-default">
            <div class="card-header">
                <h3 class="card-title">
                    {% if action == 'add' %}
                        <i class="fas fa-plus"></i>
                    {% else %}
                        <i class="fas fa-edit"></i>
                    {% endif %}
                    {{ title }}
                </h3>
            </div>

            <div class="card-body">
                {% csrf_token %}
                {% block formulario-body %}
                    {% for field in form.visible_fields %}
                        <div class="form-group">
                            <label for="email">{{ field.label }}:</label>
                            {{ field }}
                        </div>
                    {% endfor %}
                {% endblock %}
            </div>

            <div class="card-footer">
                <button type="submit" class="btn btn-primary btn-flat">
                    <i class="fas fa-save"></i> Guardar registro
                </button>
                <a href="{{ list_url }}" class="btn btn-danger btn-flat">
                    <i class="fas fa-times"></i> Cancelar
                </a>
            </div>
        </div>
    </form>



    <script>
        {% if form.errors %}
            let errors = '';
            {% for field in form %}
                {% for error in field.errors %}
                    errors += '{{ error }}\n';
                {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
                errors += '{{ error }}\n';
            {% endfor %}
            Swal.fire({
                title: 'Error!',
                text: errors,
                icon: 'error'
            });
        {% endif %}

        {% if action == 'add' %}
            $('form').on('submit', function (e) {
                e.preventDefault();
                let parameters = new FormData(this);
                submit_with_ajax(window.location.pathname, 'Notificación', '¿Estas seguro de realizar la siguiente acción?', parameters, () => {
                    Swal.fire({
                        title: 'Alerta!',
                        text: 'Registro agregado correctamente!',
                        icon: 'success',
                        timer: 1200,
                        onClose: () => {
                            location.href = '{{ list_url }}';
                        }
                    });
                });
            });
        {% else %}
            $('form').on('submit', function (e) {
                e.preventDefault();
                let parameters = new FormData(this);
                submit_with_ajax(window.location.pathname, 'Notificación', '¿Estas seguro de realizar la siguiente acción?', parameters, () => {
                    Swal.fire({
                        title: 'Alerta!',
                        text: 'Registro actualizado correctamente!',
                        icon: 'success',
                        timer: 2000,
                        onClose: () => {
                            location.href = '{{ list_url }}';
                        }
                    });
                });
            });
        {% endif %}
    </script>
{% endblock %}

templates/layouts.html
{% extends 'body.html' %}

templates/sidebar.html
{% load static %}
<div class="main-sidebar sidebar-dark-gray-dark elevation-4">
    <a href="{% url 'dashboard' %}" class="brand-link">
        <img src="{% static 'img/favicon.ico' %}"
             alt="HR Logo"
             class="brand-image img-circle "
             style="opacity: .8">
        <span class="brand-text font-weight-light">Human Recruiter</span>
    </a>
    <div class="sidebar">
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="{{ request.user.get_image }}" class="img-circle" alt="User Image">
            </div>
            <div class="info">
                <a href="{% url 'dashboard' %}" class="d-block">{{ request.user.username }}</a>
            </div>
        </div>
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" data-accordion="true">
                <li class="nav-header">Funcionamientos</li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-users"></i>
                        <p>
                            Recursos Humano
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview" style="display: none;">
                        <li class="nav-item">
                            <a href="{% url 'erp:empleados_list' %}" class="nav-link">
                                <i class="nav-icon fas fa-user-clock"></i>
                                <p>Empleados</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'erp:asistencia_list' %}" class="nav-link">
                                <i class=" nav-icon  fas fa-clock"></i>
                                <p>
                                    Asistencias
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'erp:departaments_list' %}" class="nav-link">
                                <i class=" nav-icon  fas fa-layer-group"></i>
                                <p>
                                    Departamentos
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="{% url 'erp:position_list' %}" class="nav-link">
                                <i class=" nav-icon  fas fa-suitcase"></i>
                                <p>
                                    Puestos Trabajo
                                </p>
                            </a>
                        </li>

                        <li class="nav-item">
                            <a href="{% url 'erp:turno_trabajo_list' %}" class="nav-link">
                                <i class=" nav-icon  fas fa-clock"></i>
                                <p>
                                    Horarios
                                </p>
                            </a>
                        </li>

                           <li class="nav-item">
                            <a href="{% url 'erp:vacations_list' %}" class="nav-link">
                                <i class=" nav-icon  fas fa-plane-up"></i>
                                <p>
                                    Vacaciones
                                </p>
                            </a>
                        </li>

                        <li class="nav-item">
                            <a href="{% url 'erp:descuento_list' %}" class="nav-link">
                                <i class=" nav-icon  fas fa-calculator"></i>
                                <p>
                                    Descuentos
                                </p>
                            </a>
                        </li>

                        <li class="nav-item">
                            <a href="{% url 'erp:salary_list' %}" class="nav-link">
                                <i class=" nav-icon  fas fa-money-check-alt"></i>
                                <p>
                                    Salarios
                                </p>
                            </a>
                        </li>
                    </ul>
                </li>

                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-search"></i>
                        <p>
                            Reclutadores
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="nav-treeview" style="display: none;">
                        <li class="nav-item">
                            <a href="{% url 'erp:vacante_list' %}" class="nav-link">
                                <i class="nav-icon fas fa-suitcase"></i>
                                <p>
                                    Vacantes
                                </p>
                            </a>
                        </li>

                        <li class="nav-item">
                            <a href="{% url 'erp:candidatos_list' %}" class="nav-link">
                                <i class="nav-icon fas fa-user"></i>
                                <p>

                                    Persona
                                </p>
                            </a>
                        </li>

                        <li class="nav-item">
                            <a href="{% url 'erp:select_list' %}" class="nav-link">
                                <i class="nav-icon fas fa-check-circle"></i>
                                <p>
                                    Candidatos
                                </p>
                            </a>
                        </li>

                    </ul>

                </li>

                <li class="nav-item menu-is-opening">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-lock"></i>
                        <p>
                            Seguridad
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="nav-treeview" style="display: none;">
                        <!--  Accesos  -->
                        <li class="nav-item">
                            <a href="{% url 'acceso_usuario_list' %}" class="nav-link">
                                <i class="nav-icon fas fa-user-secret"></i>
                                <p>
                                    Control de acceso
                                </p>
                            </a>
                        </li>
                        <!-- Usuarios -->
                        <li class="nav-item">
                            <a href="{% url 'user:user_list' %}" class="nav-link">
                                <i class="nav-icon fas fa-user-friends"></i>
                                <p>
                                    Usuarios
                                </p>
                            </a>
                        </li>

                    </ul>
                    {% comment %} Compañia {% endcomment %}
                
                    <li class="nav-item">
                    <a href="{% url 'erp:company_update' %}" class="nav-link">
                        <i class="fas fa-building mr-2"></i>
                        <p>
                            Compañia
                        </p>
                    </a>
                </li>

                {% comment %} Change Password {% endcomment %}
                <li class="nav-item">
                    <a href="{% url 'user:user_change_password' %}" class="nav-link">
                        <i class="fas fa-key mr-2"></i>
                        <p>
                            Editar Contraseña
                        </p>
                    </a>
                </li>
                {% comment %} Update Profile {% endcomment %}
                <li class="nav-item">
                    <a href="{% url 'user:user_profile' %}" class="nav-link">
                        <i class="fas fa-edit mr-2"></i>
                        <p>
                            Editar Perfil
                        </p>
                    </a>
                </li>
                </li>
            </ul>
        </nav>
    </div>
</div>